2025-05-24 13:54:23,125 INFO    MainThread:27220 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-05-24 13:54:23,125 INFO    MainThread:27220 [wandb_setup.py:_flush():67] Configure stats pid to 27220
2025-05-24 13:54:23,125 INFO    MainThread:27220 [wandb_setup.py:_flush():67] Loading settings from C:\Users\ming\.config\wandb\settings
2025-05-24 13:54:23,125 INFO    MainThread:27220 [wandb_setup.py:_flush():67] Loading settings from C:\Users\ming\Desktop\LDM-Reproduce\wandb\settings
2025-05-24 13:54:23,125 INFO    MainThread:27220 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-05-24 13:54:23,125 INFO    MainThread:27220 [wandb_init.py:setup_run_log_directory():647] Logging user logs to C:\Users\ming\Desktop\LDM-Reproduce\wandb\run-20250524_135423-3yp9x6rz\logs\debug.log
2025-05-24 13:54:23,125 INFO    MainThread:27220 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to C:\Users\ming\Desktop\LDM-Reproduce\wandb\run-20250524_135423-3yp9x6rz\logs\debug-internal.log
2025-05-24 13:54:23,125 INFO    MainThread:27220 [wandb_init.py:init():761] calling init triggers
2025-05-24 13:54:23,125 INFO    MainThread:27220 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'project_name': 'VAE', 'batch_size': 1, 'lr': 4.5e-06, 'weight_decay': 4.5e-06, 'optim_type': 'AdamW', 'epochs': 1, 'f': 8, 'c': 4, 'kl_weight': 1e-06, 'ckpt_path': './checkpoint/MS_COCO_VAE3.pkl', '_wandb': {}}
2025-05-24 13:54:23,125 INFO    MainThread:27220 [wandb_init.py:init():784] starting backend
2025-05-24 13:54:23,125 INFO    MainThread:27220 [wandb_init.py:init():788] sending inform_init request
2025-05-24 13:54:23,176 INFO    MainThread:27220 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2025-05-24 13:54:23,177 INFO    MainThread:27220 [wandb_init.py:init():803] backend started and connected
2025-05-24 13:54:23,179 INFO    MainThread:27220 [wandb_init.py:init():896] updated telemetry
2025-05-24 13:54:23,219 INFO    MainThread:27220 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-05-24 13:54:23,740 INFO    MainThread:27220 [wandb_init.py:init():995] starting run threads in backend
2025-05-24 13:54:24,111 INFO    MainThread:27220 [wandb_run.py:_console_start():2377] atexit reg
2025-05-24 13:54:24,111 INFO    MainThread:27220 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-05-24 13:54:24,111 INFO    MainThread:27220 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-05-24 13:54:24,111 INFO    MainThread:27220 [wandb_run.py:_redirect():2317] Redirects installed.
2025-05-24 13:54:24,114 INFO    MainThread:27220 [wandb_init.py:init():1037] run started, returning control to user process
2025-05-24 14:35:32,530 WARNING MsgRouterThr:27220 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "D:\Work_category\anaconda3_dirs\envs\pytorch-2.6.0-gpu\Lib\site-packages\wandb\sdk\interface\router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Work_category\anaconda3_dirs\envs\pytorch-2.6.0-gpu\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Work_category\anaconda3_dirs\envs\pytorch-2.6.0-gpu\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Work_category\anaconda3_dirs\envs\pytorch-2.6.0-gpu\Lib\site-packages\wandb\sdk\interface\router.py", line 70, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "D:\Work_category\anaconda3_dirs\envs\pytorch-2.6.0-gpu\Lib\site-packages\wandb\sdk\interface\router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-05-24 14:35:32,535 INFO    MsgRouterThr:27220 [mailbox.py:close():115] Closing mailbox, abandoning 1 handles.
